
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/staticfiles  # Добавьте эту строку
    # НЕ монтируем папку static - файлы будут внутри контейнера
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn fish.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_simple.conf:/etc/nginx/nginx.conf:ro
      # Монтируем ТОЛЬКО собранные статические файлы
      - static_volume:/home/app/staticfiles:ro # Та же папка в nginx  # Используем volume вместо ./staticfile
    depends_on:
      - db
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:  # Добавьте эту строк
