# Generated by Django 5.2.6 on 2025-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyresponse_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
