# Generated by Django 5.2.6 on 2025-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyresponse_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-visited_at'], 'verbose_name': 'Посещение страницы', 'verbose_name_plural': 'Посещения страниц'},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ответ на опрос', 'verbose_name_plural': 'Ответы на опрос'},
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время посещения'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='button_clicked',
            field=models.BooleanField(default=False, verbose_name='Кнопка нажата'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Отдел/Управление'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='familiar',
            field=models.CharField(max_length=20, verbose_name='Ознакомление с регламентом'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='government_body',
            field=models.CharField(max_length=100, verbose_name='Орган власти'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='password_change',
            field=models.CharField(max_length=20, verbose_name='Смена паролей'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='password_compliance',
            field=models.CharField(max_length=20, verbose_name='Соответствие пароля'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='two_factor',
            field=models.CharField(max_length=20, verbose_name='Двухфакторная аутентификация'),
        ),
    ]
