# Generated by Django 5.2.6 on 2025-10-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_pagevisit_options_alter_surveyresponse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='department',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='government_body',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='position',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
